config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
    #to save automatic email to the small letter 
    before_save {self.email = email.downcase}
    has_many :articles,dependent: :destroy
    
    validates :username, presence: true, uniqueness: true, length: {minimum:3 ,maximum:100}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, length: {maximum:100},format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController<ApplicationController

    before_action :set_user, only: [:show,:edit,:update,:destroy]
    before_action :require_user, only:[:edit,:update]
    #before_action :require_same_user, only:[:edit,:update,:destroy]

    def show

    end

    def index
        @users = ActiveRecord::Base.connection.exec_query("call get_all_user")
        ActiveRecord::Base.clear_all_connections!
        # sql = "select * from users;"
        # @users = ActiveRecord::Base.connection.exec_query(sql)
       
    end

    def new
        @user=User.new
    end

    def create 
       
        user_name = params[:user][:username]
        user_email = params[:user][:email]
        user_password = params[:user][:password]
        @user = ActiveRecord::Base.connection.exec_query("call create_user('#{user_name}','#{user_email}','#{user_password}',@userid,@cu_username)")
       
       # return username from database using SP in output...
        @current_username = ActiveRecord::Base.connection.exec_query("select @cu_username")
        current_username = @current_username.first['@cu_username']
        ActiveRecord::Base.clear_all_connections!
        flash[:notice] = "Welcome \"#{current_username}\" you have succesfully signup "
        redirect_to login_path

        ##### To get return users.id and using this fetch the username from database #################

        #@user_id_return = ActiveRecord::Base.connection.exec_query("select @userid")
        #user_id_return = @user_id_return.first['@userid']
        # user_username = ActiveRecord::Base.connection.exec_query("call get_user_username_return_byId(#{user_id_return})")
        # ActiveRecord::Base.clear_all_connections!
        #@@flash[:notice] = "Welcome \"#{user_username.first['username']}\" you have succesfully signup "
        # flash[:notice] = "Welcome \"#{current_username}\" you have succesfully signup "
        # redirect_to login_path

        # @user = User.new(user_params)
        # if @user.save
        #     flash[:notice] = "Welcome \"#{@user.username}\" you have succesfully signup "
        #     redirect_to login_path
        # else
        #     render 'new'

        # end
    end

    def edit

    end

    def update

        user_id = params[:id]
        user_name = params[:username]
        user_email = params[:email]
        @user = ActiveRecord::Base.connection.exec_query("call update_user(#{user_id},'#{user_name}','#{user_email}')")
        ActiveRecord::Base.clear_all_connections!
        flash[:notice] = "your account is updated"
        redirect_to user_path

        # if @user.update(user_params)
        #     flash[:notice] = "your account is updated"
        #     redirect_to articles_path
        # else
        #     render 'edit'
        # end

    end

    def destroy
        # @user = User.find(params[:id])
        # @user.destroy
        user_id = params[:id]
        @user = ActiveRecord::Base.connection.exec_query("call delete_user(#{user_id})")
        ActiveRecord::Base.clear_all_connections!
        session[:user_id] = nil if @user == current_user['id']
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to user_path

    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      #@user = User.find(params[:id])
        user_id = params['id']
        @user = ActiveRecord::Base.connection.exec_query("call find_user_byID(#{user_id})")
        ActiveRecord::Base.clear_all_connections!
        
    end

    def require_same_user
        if current_user['id'] != @user && !current_user.admin?
            flash[:alert]= "you can't edit or update must be looged_in user and admin both are same user and admin both.. "
            redirect_to user_path #show page
        end

    end
end

app/views/users/_form.html.erb
<div class="container">

    <div class="row justify-content-center">
        <div class="col-8">
        <%#= render 'shared/errors',obj: @user %>
            <%= form_with(model: @user,class: "shadow p-4 mb-2 bg-info rounded", local: true) do |f| %>

            <div class="form-group row">
                <%= f.label :username, class: "col-2 col-form-label text-dark" %>
                <div class="col-8">
                    <%= f.text_field :username, class: "form-control shadow rounded", placeholder: " Enter your username" %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :email, class: "col-2 col-form-label text-dark"%>
                <div class="col-8">
                    <%= f.email_field :email, class: "form-control shadow rounded",placeholder: "Enter your email address" %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :password, class: "col-2 col-form-label text-dark"%>
                <div class="col-8">
                    <%= f.password_field :password,class: "form-control shadow rounded",placeholder: "Enter your password" %>
                </div>
            </div>

            <div class="form-group text-center ">
                <%= f.submit( class: "btn btn-outline-success btn-lg")%>
                 
                
            </div>
            
        </div>
            <div class="form-group text-center ">
                <%= link_to 'login!', login_path, class: " btn btn-outline-success btn-lg"%>
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit the User</h1>

<%#= render 'form' %>
<div class="container">

    <div class="row justify-content-center">
        <div class="col-8">
        <%#= render 'shared/errors',obj: @user %>
            <%= form_with(url: user_path,class: "shadow p-4 mb-2 bg-info rounded", local: true,method: :put) do |f| %>

            <div class="form-group row">
                <%= f.label :username, class: "col-2 col-form-label text-dark" %>
                <div class="col-8">
                    <%= f.text_field :username,value: "#{@user.first['username']}", class: "form-control shadow rounded", placeholder: " Enter your username" %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :email, class: "col-2 col-form-label text-dark"%>
                <div class="col-8">
                    <%= f.email_field :email, value: "#{@user.first['email']}", class: "form-control shadow rounded",placeholder: "Enter your email address" %>
                </div>
            </div>
            <div class="form-group row">
                <%= f.label :password, class: "col-2 col-form-label text-dark"%>
                <div class="col-8">
                    <%= f.password_field :password,value: "#{@user.first['password']}",class: "form-control shadow rounded",placeholder: "Enter your password" %>
                </div>
            </div>

            <div class="form-group text-center ">
                <%= f.submit('update user',class: "btn btn-outline-success btn-lg")%>
                
            </div>
            
        </div>
            <div class="form-group text-center ">
                <%= link_to 'login!', login_path, class: " btn btn-outline-success btn-lg"%>
            </div>
        <% end %>
    </div>
</div>


<div class="text-center">
    <%= link_to '[Home Page]', articles_path, class: "text-info" %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Bloggers!</h1>





<div >
    <%= link_to 'Create a new User',signup_path, class: " text-success btn btn-outline-info"%>
    <%= link_to 'Home Page', articles_path, class: " text-success btn btn-outline-info"%>
</div>


<div class="container ">


    <% @users.each do |user| %>
        <div class="row justify-content-md-center ">
            <div class="col-8 mt-4 ">


                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= user['username'] %>
                    </div>
                    <div class="card-body">

                        <p class="card-text">
                            <%# helper method called here 'get_user_articles'............%>
                            <%= pluralize(get_user_articles(user['id']).count,"article") %>
                        </p>
                        <%= link_to 'view Profile',user_path(user['id']),class: "btn btn-outline-info"%>
                        <% if logged_in? %>
                            <% if user['id'] == current_user['id'] %>
                                <%= link_to 'Edit Profile',edit_user_path(user['id']),class: "btn btn-outline-info"%>
                            <% end %>
                            <% if current_user.admin? || current_user['id'] == user['id']%>
                                <%= link_to "Delete", user_path(user['id']), class: "btn btn-outline-danger",method: :delete,data: {confirm: "Are you sure to delete account ?"} %>
                            <% end %>
                        <% end%>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user['created_at']) %> ago</small>
                    </div>
                </div>

            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign up for Rails Blog!</h1>

<%= render 'form' %>

<div class="text-center">
    <%= link_to '[Home Page]', articles_path, class: "text-info"%>
    
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.first['username'] %>'s profile</h1>