config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name

    has_many :article_categories
    has_many :articles, through: :article_categories
    

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    #before_action :require_admin, except: [:index,:show]
    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def index
        
        @categories = ActiveRecord::Base.connection.exec_query("call get_categories")
        ActiveRecord::Base.clear_all_connections!
        #@categories = Category.paginate(page: params[:page],per_page: 5)

    end

    def edit
        #@category =Category.find(params[:id])
        
        category_id = params[:id]
       
        @categories = ActiveRecord::Base.connection.exec_query("call show_category_details_by_id(#{category_id})").first
    
        ActiveRecord::Base.clear_all_connections!

    end

    def update
        #@category =Category.find(params[:id])
        
        category_id = params[:id]
        category_name = params[:name]
        @category = ActiveRecord::Base.connection.exec_query("call update_category(#{category_id},'#{category_name}')")
        ActiveRecord::Base.clear_all_connections!
        flash[:notice] = "Category was updated successfully.."
        redirect_to category_path
  
        # if @category.update(category_params)
            
        #     flash[:notice] = "Category was updated successfully.."
        #     redirect_to @category

        # else
        #     render 'edit'
            
        # end

    end

    def show
       
        category_id = params[:id]
        @category = ActiveRecord::Base.connection.exec_query("call show_category_by_id(#{category_id})")
        ActiveRecord::Base.clear_all_connections!
        @articles = ActiveRecord::Base.connection.exec_query("call count_all_articles_of_categories(#{category_id})")
        ActiveRecord::Base.clear_all_connections!
       
        

    end


    private
    def category_params
        params.require(:category).permit(:name)
    end


    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admin can perform that action"
            redirect_to categories_path
        end

    end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category),class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%#= render 'shared/errors', obj: @category %>
<%= form_with(model: @category,class: "shadow p-4 mb-2 bg-info rounded", local: true) do |f| %>

    <div class="form-group row">
        <%= f.label :name, "Category name", class: "col-2 col-form-label text-dark" %>
        <div class="col-8">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: " Enter your name" %>
        </div>
    </div>


    <div class="form-group text-center ">
        <%= f.submit 'create category',class: "btn btn-outline-light btn-lg" %>    
    </div>
<% end %>


    
 
<div class="text-center">
    <%= link_to '[Home Page]', articles_path, class: "text-info"%>
    
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4"> edit category!</h1>

<div class="container">

    <div class="row justify-content-center">
        <div class="col-8">
          
           
        
            <%#= render 'shared/errors', obj: @category %>
           
            <%= form_with(url: category_path(@categories['id']),class: "shadow p-4 mb-2 bg-info rounded", local: true, method: :put) do |f| %>

                <div class="form-group row">
                    <%= f.label :name, "Category name", class: "col-2 col-form-label text-dark" %>
                    <div class="col-8">
                        <%= f.text_field :name, value: "#{@categories['name']}",class: "form-control shadow rounded", placeholder: " Enter your name" %>
                    </div>
                </div>


                <div class="form-group text-center ">
                    <%= f.submit 'update category',class: "btn btn-outline-light btn-lg" %>    
                </div>
            <% end %>


                
            
            <div class="text-center">
                <%= link_to '[Home Page]', articles_path, class: "text-info"%>
                
            </div>



        </div>

        
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">categories!</h1>

<p>
    <%= link_to 'Create a new category', new_category_path, class: " text-success btn btn-outline-info"%>
</p>
<div class="container ">


    <% @categories.each do |category| %>
        <div class="row justify-content-md-center ">
            <div class="col-4 mt-4 ">


                <div class="card text-center shadow mb-5 bg-white rounded">
                   
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to category['name'],category_path(category['id']),class: "text-success" %>
                        </h5>
                         <p class="card-text">
                            <%= pluralize(get_category_articles(category['id']).count,"article") %>
                        </p>
                    </div>
                    <div class="card-footer text-muted">
                        <small>created <%= time_ago_in_words(category['created_at']) %> ago, edited <%= time_ago_in_words(category['updated_at']) %> </small>
                    </div>
                </div>

            </div>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4"> create a new category!</h1>

<div class="container">

    <div class="row justify-content-center">
        <div class="col-8">
            <%= render 'form' %>
        </div>

        
    </div>
</div>

app/views/categories/show.html.erb
<h2 class="text-center mt-4">Category: <%= @category.first['name'] %>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category.first['id']), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>


<%#= render 'articles/article' %>
<p>
    <%= link_to 'Create a new article', new_article_path, class: " text-success btn btn-outline-info"%>
</p>
<div class="container ">


  
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center ">
            <div class="col-8 mt-4 ">
                

                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                  
                    <% article_user = article_join_user(article['id']) %>
                       
                        by <%= link_to article_user.first['username'],user_path(article['user_id']) %>
                        
                     
                   
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to article['title'],article_path(article['id']),class: "text-success" %>
                        </h5>
                        <p class="card-text">
                            <!--truncate () means summery of anything and we can set limit(length) of character-->
                            <%= truncate(article['description'],length: 20) %>
                        </p>

                        <%= link_to 'View',article_path(article['id']),class: "btn btn-outline-success"%>
                        <% if logged_in? && (article['user'] == current_user || current_user.admin?)%>
                            <%= link_to 'edit',edit_article_path(article['id']),class: "btn btn-outline-info"%>
                            <%= link_to 'Delete',article_path(article['id']),class: "btn btn-outline-danger",method: :delete, data: {confirm: "Are you sure?"}%>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>created <%= time_ago_in_words(article['created_at']) %> ago, edited <%= time_ago_in_words(article['updated_at']) %> </small>
                    </div>
                </div>

            </div>
        </div>
    <% end %>
</div>