config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
        <div class="container text-center">
        
            <small>Copyright &copy; <%= link_to "Google", "https://www.google.com/", class: "text-white" %></small>
            
        </div>
</footer> 

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name,msg|%>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
        
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!--<a class="navbar-brand" id="logo" href="#">Rails Blog</a>-->
  <%= link_to "Rails Blog",root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item  active">
        
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
        <%= link_to "Articles",articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Blogger",users_path,class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Categories",categories_path,class: "nav-link" %>
      </li>
      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         
          <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
      </li>
-->
      <% if logged_in? %>
        
        <li class="nav-item text-white">
          <%= "(admin)"if current_user.admin? %>
        </li>
        <li class="nav-item text-white">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'logout', logout_path, class: "nav-link", method: :delete %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'login', login_path, class: "nav-link "%>
          
        </li>
        <li class="nav-item">
          <%= link_to 'signup',signup_path, class:"nav-link"%>
        </li>

      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<!-- for sticky footer class use (d-flex flex-column)-->
  <body class="d-flex flex-column" id="page-content">
 


  

    <!--  partials the _navigation.html.erb  -->
      <%= render 'layouts/navigation' %>
    
    
    <div id="page-content">
   
      <%= render 'layouts/messages' %>
      <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>